//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_picross : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean SwitchMode
        {
            get
            {
                return SteamVR_Actions.picross_SwitchMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean PerformAction
        {
            get
            {
                return SteamVR_Actions.picross_PerformAction;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Rotate
        {
            get
            {
                return SteamVR_Actions.picross_Rotate;
            }
        }
        
        public virtual SteamVR_Action_Boolean HideLayer
        {
            get
            {
                return SteamVR_Actions.picross_HideLayer;
            }
        }
        
        public virtual SteamVR_Action_Boolean ShowLayer
        {
            get
            {
                return SteamVR_Actions.picross_ShowLayer;
            }
        }
        
        public virtual SteamVR_Action_Single PerformActionFloat
        {
            get
            {
                return SteamVR_Actions.picross_PerformActionFloat;
            }
        }
        
        public virtual SteamVR_Action_Single SwitchModeFloat
        {
            get
            {
                return SteamVR_Actions.picross_SwitchModeFloat;
            }
        }
    }
}
