//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_picross : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean RotateUp
        {
            get
            {
                return SteamVR_Actions.picross_RotateUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotateLeft
        {
            get
            {
                return SteamVR_Actions.picross_RotateLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotateRight
        {
            get
            {
                return SteamVR_Actions.picross_RotateRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotateDown
        {
            get
            {
                return SteamVR_Actions.picross_RotateDown;
            }
        }
    }
}
